/* Generated By:JJTree: Do not edit this line. ASTMDPrefix.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.zippyrate.dsls.md.parser;

public
class ASTMDPrefix extends SimpleNode {

  // The following variables were manually added to this JJTree-generated node file.
  // This file was then copied from the generated sources directory to the project 
  // source tree to add it to source control and to prevent JJTree from overwriting it upon reinvocation.
  public String prefix;

  public ASTMDPrefix(int id) {
    super(id);
  }

  public ASTMDPrefix(MDParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(MDParserVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9ba18513685982c56a3c8ebcecf2ab0 (do not edit this line) */
